---
# Source: applications/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: sample-prod-service
  namespace: sample
spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: sample-prod
  type: ClusterIP
---
# Source: applications/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-prod
  namespace: sample
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: sample-prod
  template:
    metadata:
      labels:
        app: sample-prod
    spec:
      serviceAccountName: sample-prod-account
      containers:
        - name: sample-prod
          image: registry.rkddmscks.site/sample-prod:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: sample-prod
      imagePullSecrets:
        - name: imagepullsecret
---
# Source: applications/templates/ingressroute.yaml
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sample-prod-ingressroute
  namespace: sample
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`sample-prod.rkddmscks.site`)
      kind: Rule
      services:
        - name: sample-prod-service
          port: 80
      middlewares:
        - name: sample-prod-ratelimit
        - name: sample-prod-buffering
---
# Source: applications/templates/middleware.yaml
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: sample-prod-ratelimit
  namespace: sample
spec:
  rateLimit:
    average: 200
    burst: 200
    period: 90s
    sourceCriterion:
      ipStrategy:
        depth: 1
---
# Source: applications/templates/middleware.yaml
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: sample-prod-buffering
  namespace: sample
spec:
  buffering:
    maxRequestBodyBytes: 90000
    memRequestBodyBytes: 90000
    maxResponseBodyBytes: 90000
    memResponseBodyBytes: 90000
    retryExpression: "IsNetworkError()"
---
# Source: applications/templates/vault-auth.yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: sample-prod-auth
  namespace: sample
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: injunweb-role
    serviceAccount: sample-prod-account
    audiences:
      - vault
---
# Source: applications/templates/vault-static-secret.yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: sample-prod-secret
  namespace: sample
spec:
  type: kv-v1
  mount: injunweb-kv
  path: sample-prod
  destination:
    name: sample-prod
    create: true
  vaultAuthRef: sample-prod/sample-prod-auth
  refreshAfter: 1m
  rolloutRestartTargets:
    - kind: Deployment
      name: sample-prod
