# Webhook IngressRoute GitOps 관리를 위한 Application 설정
# Argo CD가 Webhook Ingress 설정을 어떻게 관리할지 정의하는 매니페스트
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rapid-workflow-webhook
  namespace: pipeline-system
  # 리소스 식별 및 그룹화를 위한 레이블
  labels:
    app.kubernetes.io/name: rapid-workflow-webhook
    app.kubernetes.io/part-of: rapid-platform
    app.kubernetes.io/component: ingress
  # 리소스 설명을 위한 어노테이션
  annotations:
    description: "Rapid Platform의 Workflow Webhook Ingress 구성"
spec:
  # Argo CD 프로젝트 지정
  project: default
  # 소스 저장소 설정
  source:
    # Webhook 설정이 포함된 Git 저장소 URL
    repoURL: https://github.com/devteam-rapid/rapid-services-repo.git
    # 동기화할 브랜치
    targetRevision: main
    # 저장소 내 설정 파일 경로
    path: workflow-webhook
  # 대상 클러스터 설정
  destination:
    # 현재 클러스터 대상
    server: https://kubernetes.default.svc
    # pipeline-system 네임스페이스에 배포
    namespace: pipeline-system
  # 동기화 정책 설정
  syncPolicy:
    automated:
      # Git에 없는 리소스 자동 삭제
      prune: true
      # 클러스터 상태가 Git과 다를 때 자동 동기화
      selfHeal: true
    # 추가 동기화 옵션
    syncOptions:
      # 네임스페이스가 없으면 생성
      - CreateNamespace=true
      # 리소스 삭제 전 완료 대기
      - PrunePropagationPolicy=foreground
      # 새 리소스 준비 완료 후 삭제 진행
      - PruneLast=true
      # 수동 관리되는 필드 무시
      - RespectIgnoreDifferences=true