apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.appName }}
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      serviceAccountName: {{ .Values.appName }}-account
      containers:
        - name: {{ .Values.appName }}
          image: registry.rkddmscks.site/{{ .Values.appName }}:{{ .Values.imageTag }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.port }}
          envFrom:
            - secretRef:
                name: {{ .Values.appName }}
      imagePullSecrets:
        - name: imagepullsecret