apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.appName }}-ingressroute
  namespace: {{ .Values.namespace }}
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`{{ .Values.hostname }}`)
      kind: Rule
      services:
        - name: {{ .Values.appName }}-service
          port: 80
      middlewares:
        - name: {{ .Values.appName }}-ratelimit
        - name: {{ .Values.appName }}-buffering