apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ .Values.appName }}-secret
  namespace: {{ .Values.namespace }}
spec:
  type: kv-v2
  mount: rapid
  path: {{ .Values.appName }}
  destination:
    name: {{ .Values.appName }}
    create: true
  vaultAuthRef: {{ .Values.appName }}/{{ .Values.appName }}-auth
  refreshAfter: 1m
  rolloutRestartTargets:
    - kind: Deployment
      name: {{ .Values.appName }}