apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: {{ .Values.appName }}-auth
  namespace: {{ .Values.namespace }}
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: {{ .Values.appName }}-role
    serviceAccount: {{ .Values.appName }}-account
    audiences:
      - vault