# Services GitOps 관리를 위한 Application 설정
# Argo CD가 Rapid 서비스 저장소를 어떻게 관리할지 정의하는 매니페스트
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
 # Application의 이름
 name: rapid-services
 # 배포될 네임스페이스
 namespace: pipeline-system
 # 리소스 식별을 위한 레이블
 labels:
   app.kubernetes.io/name: rapid-services
   app.kubernetes.io/part-of: rapid-platform
   app.kubernetes.io/component: core
 # 추가 설명 정보
 annotations:
   description: "Rapid Platform의 서비스 구성 관리"
spec:
 # Argo CD 프로젝트 지정
 project: rapid-application

 # 소스 저장소 설정
 source:
   # 서비스 정의가 포함된 Git 저장소 URL
   repoURL: https://github.com/devteam-rapid/rapid-services-repo.git
   # 동기화할 브랜치/태그
   targetRevision: main
   # 저장소 내 경로
   path: ./platform
   # 디렉토리 처리 설정
   directory:
     # Platform 하위 모든 디렉토리 포함
     recurse: true
   # GitHub 저장소 접근을 위한 인증 설정
   githubSecret:
     # pipeline-system 네임스페이스의 시크릿 이름
     name: github-token
     # 시크릿에서 사용할 키
     key: token

 # 대상 클러스터 설정
 destination:
   # 현재 클러스터를 대상으로 지정
   server: https://kubernetes.default.svc
   # pipeline-system 네임스페이스에 배포
   namespace: pipeline-system

 # 동기화 정책 설정
 syncPolicy:
   # 자동화 설정
   automated:
     # Git에 없는 리소스 자동 삭제
     prune: true
     # 클러스터 상태가 Git과 다를 때 자동 동기화
     selfHeal: true
   # 추가 동기화 옵션
   syncOptions:
     # 네임스페이스가 없으면 자동 생성
     - CreateNamespace=true
     # 리소스 삭제 전 완료 대기
     - PrunePropagationPolicy=foreground
     # 새 리소스 준비 완료 후 삭제 진행
     - PruneLast=true